const CT_HOTELS=[
  {name:"Salamanca Inn",city:"HBA",provider:"SALHBA"},
  {name:"Nightelier Devonport",city:"DPO",provider:"GATDPO"},
  {name:"Peppers Silo Hotel",city:"LST",provider:"PSHLST"},
  {name:"Hotel Verge Launceston",city:"LST",provider:"VERLST"},
  {name:"The Old Woolstore Apartment Hotel",city:"HBA",provider:"OLDHBA"},
  {name:"Peppers Seaport Hotel",city:"LST",provider:"PEPLST"},
  {name:"Doubletree By Hilton Hobart",city:"HBA",provider:"DOUHBA"},
  {name:"Beachfront Voyager Motor Inn",city:"BWT",provider:"FWBWT1"},
  {name:"Wrest Point",city:"HBA",provider:"LMHBA3"},
  {name:"Hotel Grand Chancellor Hobart",city:"HBA",provider:"LMHBA4"},
  {name:"Crowne Plaza Hobart",city:"HBA",provider:"CRWHBA"},
  {name:"Ikon Hotel",city:"BWT",provider:"IKOBWT"},
  {name:"Movenpick Hotel Hobart",city:"HBA",provider:"MVPHBA"},
  {name:"Mantra Charles Hotel",city:"LST",provider:"HOTLST"},
  {name:"The Sebel Launceston",city:"LST",provider:"SBLLST"},
  {name:"Novotel Devonport",city:"DPO",provider:"DPONOV"},
  {name:"Silver Hills Motel",city:"UEE",provider:"BWBWT1"},
  {name:"Panorama Hotel St Helens",city:"HLS",provider:"TIDLST"},
  {name:"Tall Timbers Tasmania",city:"SIO",provider:"TALSIO1"},
  {name:"One North Terrace",city:"BWT",provider:"BWTON1"},
  {name:"Country Club Villas",city:"LST",provider:"COULST"},
  {name:"Burnie Central Townhouse Hotel",city:"BWT",provider:"BURBRN"},
  {name:"Barclay Motor Inn",city:"DPO",provider:"BARDPO2"},
  {name:"Bridport Beach Cottages",city:"TZB",provider:"ZZBRID"},
  {name:"Swansea Holiday Park Tasmania",city:"HBA",provider:"SWALST"},
  {name:"Beachfront Bicheno",city:"HLS",provider:"BICBIC"},
  {name:"Tasman Holiday Parks St Helens",city:"HLS",provider:"NRMHLS"},
  {name:"Strahan Village",city:"LST",provider:"LSTSV1"},
  {name:"Riverfront Motel And Villas",city:"HBA",provider:"RIVHBA2"},
  {name:"Tullah Lakeside Lodge",city:"UEE",provider:"TLCBWT"}
];

const CT_BOOKERS=[
  {name:"ABBY HAY",card:"VI4715********9821/EXP0929",si:[{label:"Room bond and parking",value:"ABBY HAY ROOM BOND AND PARKING"},{label:"Room meals bond parking",value:"ABBY HAY ROOM MEALS BOND PARKING"}]},
  {name:"BRANDI SOKOLSKI",card:"VI4715********0293/EXP0529",si:[{label:"Room bond and parking",value:"BRANDI SOKOLSKI ROOM BOND AND PARKING"},{label:"Room meals bond and parking",value:"BRANDI SOKOLSKI ROOM MEALS BOND AND PARKING"}]},
  {name:"BRIDGET BUGG",card:"VI4715********9201/EXP0726",si:[{label:"Room meals bond parking",value:"BRIDGET BUGG ROOM MEALS BOND PARKING"},{label:"Room bond and parking",value:"BRIDGET BUGG ROOM BOND AND PARKING"}]},
  {name:"CHELSEA TOPIA",card:"VI4715********2627/EXP0628",si:[{label:"Room bond and parking",value:"CHELSEA TOPIA ROOM BOND AND PARKING"},{label:"Room meals bond parking",value:"CHELSEA TOPIA ROOM MEALS BOND PARKING"}]},
  {name:"CHLOE VAROVCIC",card:"VI4715********8920/EXP0329",si:[{label:"Room meals bond parking",value:"CHLOE VAROVCIC ROOM MEALS BOND PARKING"},{label:"Room bond and parking",value:"CHLOE VAROVCIC ROOM BOND AND PARKING"}]},
  {name:"CINDY LEWIS BRYAN",card:"VI4715********7215/EXP0328",si:[{label:"Room bond and parking",value:"CINDY LEWIS BRYAN ROOM BOND AND PARKING"},{label:"Room meals bond and parking",value:"CINDY LEWIS BRYAN ROOM MEALS BOND AND PARKING"}]},
  {name:"COLETTE GOODMAN",card:"VI4715********2544/EXP1128",si:[{label:"Room meals bond parking",value:"COLETTE GOODMAN ROOM MEALS BOND PARKING"},{label:"Room bond and parking",value:"COLETTE GOODMAN ROOM BOND AND PARKING"}]},
  {name:"EMILY FRERK",card:"VI4715********5228/EXP0128",si:[{label:"Room bond and parking",value:"EMILY FRERK ROOM BOND AND PARKING"},{label:"Room meals bond and parking",value:"EMILY FRERK ROOM MEALS BOND AND PARKING"}]},
  {name:"EMMA NICHOLS",card:"VI4715********5756/EXP1228",si:[{label:"Room bond and parking",value:"EMMA NICHOLS ROOM BOND AND PARKING"},{label:"Room meals bond and parking",value:"EMMA NICHOLS ROOM MEALS BOND AND PARKING"}]},
  {name:"GAIL JEPSON",card:"VI4715********7673/EXP0827",si:[{label:"Room bond and parking",value:"GAIL JEPSON ROOM BOND AND PARKING"},{label:"Room meals bond and parking",value:"GAIL JEPSON ROOM MEALS BOND AND PARKING"}]},
  {name:"JODI REDPATH",card:"VI4715********0237/EXP0826",si:[{label:"Room bond and parking",value:"JODI REDPATH ROOM BOND AND PARKING"},{label:"Room meals bond parking",value:"JODI REDPATH ROOM MEALS BOND PARKING"}]},
  {name:"KAIDY LAGEREWSKIJ",card:"VI4715********6535/EXP0726",si:[{label:"Room bond and parking",value:"KAIDY LAGEREWSKIJ ROOM BOND AND PARKING"},{label:"Room meals bond parking",value:"KAIDY LAGEREWSKIJ ROOM MEALS BOND PARKING"}]},
  {name:"KELLY DANIELS",card:"VI4715********5153/EXP0329",si:[{label:"Room bond and parking",value:"KELLY DANIELS ROOM BOND AND PARKING"},{label:"Room meals bond parking",value:"KELLY DANIELS ROOM MEALS BOND PARKING"}]},
  {name:"LAUREN NICOLLE",card:"VI4715********7166/EXP0626",si:[{label:"Room bond and parking",value:"LAUREN NICOLLE ROOM BOND AND PARKING"},{label:"Room meals bond parking",value:"LAUREN NICOLLE ROOM MEALS BOND PARKING"}]},
  {name:"MICHELE PERCY",card:"VI4715********7174/EXP0726",si:[{label:"Room meals bond parking",value:"MICHELE PERCY ROOM MEALS BOND PARKING"},{label:"Room bond and parking",value:"MICHELE PERCY ROOM BOND AND PARKING"}]},
  {name:"PAYING OWN ACCOUNT",card:null,si:[{label:"Paying own account during stay",value:"PAYING OWN ACCOUNT DURING STAY"}]},
  {name:"SARAH GREAVES",card:"VI4715********3097/EXP0227",si:[{label:"Room bond and parking",value:"SARAH GREAVES ROOM BOND AND PARKING"},{label:"Room meals bond parking",value:"SARAH GREAVES ROOM MEALS BOND PARKING"}]},
  {name:"TANYA BENNETT",card:"VI4715********8431/EXP1226",si:[{label:"Room bond and parking",value:"TANYA BENNETT ROOM BOND AND PARKING"},{label:"Room meals bond and parking",value:"TANYA BENNETT ROOM MEALS BOND AND PARKING"}]},
  {name:"TERSIA DERCKSEN",card:"VI4715********8415/EXP1026",si:[{label:"Room bond and parking",value:"TERSIA DERCKSEN ROOM BOND AND PARKING"},{label:"Room meals bond parking",value:"TERSIA DERCKSEN ROOM MEALS BOND PARKING"}]}
];
