const CT_HOTELS=[
  {name:"Salamanca Inn",city:"HBA",provider:"SALHBA"},
  {name:"Nightelier Devonport",city:"DPO",provider:"GATDPO"},
  {name:"Peppers Silo Hotel",city:"LST",provider:"PSHLST"},
  {name:"Hotel Verge Launceston",city:"LST",provider:"VERLST"},
  {name:"The Old Woolstore Apartment Hotel",city:"HBA",provider:"OLDHBA"},
  {name:"Peppers Seaport Hotel",city:"LST",provider:"PEPLST"},
  {name:"Doubletree By Hilton Hobart",city:"HBA",provider:"DOUHBA"},
  {name:"Beachfront Voyager Motor Inn",city:"BWT",provider:"FWBWT1"},
  {name:"Wrest Point",city:"HBA",provider:"LMHBA3"},
  {name:"Hotel Grand Chancellor Hobart",city:"HBA",provider:"LMHBA4"},
  {name:"Crowne Plaza Hobart",city:"HBA",provider:"CRWHBA"},
  {name:"Ikon Hotel",city:"BWT",provider:"IKOBWT"},
  {name:"Movenpick Hotel Hobart",city:"HBA",provider:"MVPHBA"},
  {name:"Mantra Charles Hotel",city:"LST",provider:"HOTLST"},
  {name:"The Sebel Launceston",city:"LST",provider:"SBLLST"},
  {name:"Novotel Devonport",city:"DPO",provider:"DPONOV"},
  {name:"Silver Hills Motel",city:"UEE",provider:"BWBWT1"},
  {name:"Panorama Hotel St Helens",city:"HLS",provider:"TIDLST"},
  {name:"Tall Timbers Tasmania",city:"SIO",provider:"TALSIO1"},
  {name:"One North Terrace",city:"BWT",provider:"BWTON1"},
  {name:"Country Club Villas",city:"LST",provider:"COULST"},
  {name:"Burnie Central Townhouse Hotel",city:"BWT",provider:"BURBRN"},
  {name:"Barclay Motor Inn",city:"DPO",provider:"BARDPO2"},
  {name:"Bridport Beach Cottages",city:"TZB",provider:"ZZBRID"},
  {name:"Swansea Holiday Park Tasmania",city:"HBA",provider:"SWALST"},
  {name:"Beachfront Bicheno",city:"HLS",provider:"BICBIC"},
  {name:"Tasman Holiday Parks St Helens",city:"HLS",provider:"NRMHLS"},
  {name:"Strahan Village",city:"LST",provider:"LSTSV1"},
  {name:"Riverfront Motel And Villas",city:"HBA",provider:"RIVHBA2"},
  {name:"Tullah Lakeside Lodge",city:"UEE",provider:"TLCBWT"}
];

const CT_BOOKERS=[
  {name:"ABBY HAY",last4:"9821",expiry:"0929",bond:"ABBY HAY ROOM BOND AND PARKING",meals:"ABBY HAY ROOM MEALS BOND AND PARKING"},
  {name:"BRANDI SOKOLSKI",last4:"0293",expiry:"0529",bond:"BRANDI SOKOLSKI ROOM BOND AND PARKING",meals:"BRANDI SOKOLSKI ROOM MEALS BOND AND PARKING"},
  {name:"BRIDGET BUGG",last4:"9201",expiry:"0726",bond:"BRIDGET BUGG ROOM BOND AND PARKING",meals:"BRIDGET BUGG ROOM MEALS BOND AND PARKING"},
  {name:"CHELSEA TOPIA",last4:"2627",expiry:"0628",bond:"CHELSEA TOPIA ROOM BOND AND PARKING",meals:"CHELSEA TOPIA ROOM MEALS BOND AND PARKING"},
  {name:"CINDY LEWIS BRYAN",last4:"7215",expiry:"0328",bond:"CINDY LEWIS BRYAN ROOM BOND AND PARKING",meals:"CINDY LEWIS BRYAN ROOM MEALS BOND AND PARKING"},
  {name:"COLETTE GOODMAN",last4:"2544",expiry:"1128",bond:"COLETTE GOODMAN ROOM BOND AND PARKING",meals:"COLETTE GOODMAN ROOM MEALS BOND AND PARKING"},
  {name:"EMILY FRERK",last4:"5228",expiry:"0128",bond:"EMILY FRERK ROOM BOND AND PARKING",meals:"EMILY FRERK ROOM MEALS BOND AND PARKING"},
  {name:"EMMA NICHOLS",last4:"5756",expiry:"1228",bond:"EMMA NICHOLS ROOM BOND AND PARKING",meals:"EMMA NICHOLS ROOM MEALS BOND AND PARKING"},
  {name:"GAIL JEPSON",last4:"7673",expiry:"0827",bond:"GAIL JEPSON ROOM BOND AND PARKING",meals:"GAIL JEPSON ROOM MEALS BOND AND PARKING"},
  {name:"JODI REDPATH",last4:"0237",expiry:"0826",bond:"JODI REDPATH ROOM BOND AND PARKING",meals:"JODI REDPATH ROOM MEALS BOND AND PARKING"},
  {name:"KAIDY LAGEREWSKIJ",last4:"6535",expiry:"0726",bond:"KAIDY LAGEREWSKIJ ROOM BOND AND PARKING",meals:"KAIDY LAGEREWSKIJ ROOM MEALS BOND AND PARKING"},
  {name:"KELLY DANIELS",last4:"5153",expiry:"0329",bond:"KELLY DANIELS ROOM BOND AND PARKING",meals:"KELLY DANIELS ROOM MEALS BOND AND PARKING"},
  {name:"LAUREN NICOLLE",last4:"7166",expiry:"0626",bond:"LAUREN NICOLLE ROOM BOND AND PARKING",meals:"LAUREN NICOLLE ROOM MEALS BOND AND PARKING"},
  {name:"MICHELE PERCY",last4:"7174",expiry:"0726",bond:"MICHELE PERCY ROOM BOND AND PARKING",meals:"MICHELE PERCY ROOM MEALS BOND AND PARKING"},
  {name:"SARAH GREAVES",last4:"3097",expiry:"0227",bond:"SARAH GREAVES ROOM BOND AND PARKING",meals:"SARAH GREAVES ROOM MEALS BOND AND PARKING"},
  {name:"TANYA BENNETT",last4:"8431",expiry:"1226",bond:"TANYA BENNETT ROOM BOND AND PARKING",meals:"TANYA BENNETT ROOM MEALS BOND AND PARKING"},
  {name:"TERSIA DERCKSEN",last4:"8415",expiry:"1026",bond:"TERSIA DERCKSEN ROOM BOND AND PARKING",meals:"TERSIA DERCKSEN ROOM MEALS BOND AND PARKING"},
  {name:"PAYING OWN ACCOUNT",last4:null,expiry:null,bond:null,meals:null}
];
